/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProjectCustomAttributesTemplatesFilterModel
import org.openapitools.client.models.CustomAttributeTypesEnum

class ProjectCustomAttributesTemplatesFilterModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectCustomAttributesTemplatesFilterModel
        //val modelInstance = ProjectCustomAttributesTemplatesFilterModel()

        // to test the property `name` - Name of custom attribute template
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `customAttributeTypes` - Collection of custom attributes types
        should("test customAttributeTypes") {
            // uncomment below to test the property
            //modelInstance.customAttributeTypes shouldBe ("TODO")
        }

    }
}
