/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProjectTestPlansFilterModel
import org.openapitools.client.models.DateTimeRangeSelectorModel
import org.openapitools.client.models.TestPlanStatusModel

class ProjectTestPlansFilterModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectTestPlansFilterModel
        //val modelInstance = ProjectTestPlansFilterModel()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `build`
        should("test build") {
            // uncomment below to test the property
            //modelInstance.build shouldBe ("TODO")
        }

        // to test the property `productName`
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `globalIds`
        should("test globalIds") {
            // uncomment below to test the property
            //modelInstance.globalIds shouldBe ("TODO")
        }

        // to test the property `isLocked`
        should("test isLocked") {
            // uncomment below to test the property
            //modelInstance.isLocked shouldBe ("TODO")
        }

        // to test the property `lockedDate`
        should("test lockedDate") {
            // uncomment below to test the property
            //modelInstance.lockedDate shouldBe ("TODO")
        }

        // to test the property `automaticDurationTimer`
        should("test automaticDurationTimer") {
            // uncomment below to test the property
            //modelInstance.automaticDurationTimer shouldBe ("TODO")
        }

        // to test the property `createdByIds`
        should("test createdByIds") {
            // uncomment below to test the property
            //modelInstance.createdByIds shouldBe ("TODO")
        }

        // to test the property `createdDate`
        should("test createdDate") {
            // uncomment below to test the property
            //modelInstance.createdDate shouldBe ("TODO")
        }

        // to test the property `startDate`
        should("test startDate") {
            // uncomment below to test the property
            //modelInstance.startDate shouldBe ("TODO")
        }

        // to test the property `endDate`
        should("test endDate") {
            // uncomment below to test the property
            //modelInstance.endDate shouldBe ("TODO")
        }

        // to test the property `tagNames`
        should("test tagNames") {
            // uncomment below to test the property
            //modelInstance.tagNames shouldBe ("TODO")
        }

        // to test the property `attributes`
        should("test attributes") {
            // uncomment below to test the property
            //modelInstance.attributes shouldBe ("TODO")
        }

        // to test the property `isDeleted`
        should("test isDeleted") {
            // uncomment below to test the property
            //modelInstance.isDeleted shouldBe ("TODO")
        }

    }
}
