/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PublicTestRunModel
import org.openapitools.client.models.AutoTestModel
import org.openapitools.client.models.ConfigurationModel
import org.openapitools.client.models.PublicTestPointModel

class PublicTestRunModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PublicTestRunModel
        //val modelInstance = PublicTestRunModel()

        // to test the property `testRunId`
        should("test testRunId") {
            // uncomment below to test the property
            //modelInstance.testRunId shouldBe ("TODO")
        }

        // to test the property `testPlanGlobalId`
        should("test testPlanGlobalId") {
            // uncomment below to test the property
            //modelInstance.testPlanGlobalId shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `configurations`
        should("test configurations") {
            // uncomment below to test the property
            //modelInstance.configurations shouldBe ("TODO")
        }

        // to test the property `autoTests`
        should("test autoTests") {
            // uncomment below to test the property
            //modelInstance.autoTests shouldBe ("TODO")
        }

        // to test the property `testPoints`
        should("test testPoints") {
            // uncomment below to test the property
            //modelInstance.testPoints shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `testPlanId`
        should("test testPlanId") {
            // uncomment below to test the property
            //modelInstance.testPlanId shouldBe ("TODO")
        }

        // to test the property `productName`
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `build`
        should("test build") {
            // uncomment below to test the property
            //modelInstance.build shouldBe ("TODO")
        }

        // to test the property `customParameters`
        should("test customParameters") {
            // uncomment below to test the property
            //modelInstance.customParameters shouldBe ("TODO")
        }

        // to test the property `testRunDescription`
        should("test testRunDescription") {
            // uncomment below to test the property
            //modelInstance.testRunDescription shouldBe ("TODO")
        }

    }
}
