/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SearchCustomAttributeTemplateGetModel
import org.openapitools.client.models.CustomAttributeModel
import org.openapitools.client.models.ProjectShortestModel

class SearchCustomAttributeTemplateGetModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchCustomAttributeTemplateGetModel
        //val modelInstance = SearchCustomAttributeTemplateGetModel()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `isDeleted`
        should("test isDeleted") {
            // uncomment below to test the property
            //modelInstance.isDeleted shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `projectShortestModels`
        should("test projectShortestModels") {
            // uncomment below to test the property
            //modelInstance.projectShortestModels shouldBe ("TODO")
        }

        // to test the property `customAttributeModels`
        should("test customAttributeModels") {
            // uncomment below to test the property
            //modelInstance.customAttributeModels shouldBe ("TODO")
        }

    }
}
