/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TagSelectModel
import org.openapitools.client.models.TagExtractionModel
import org.openapitools.client.models.TagsFilterModel

class TagSelectModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TagSelectModel
        //val modelInstance = TagSelectModel()

        // to test the property `filter`
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

        // to test the property `extractionModel`
        should("test extractionModel") {
            // uncomment below to test the property
            //modelInstance.extractionModel shouldBe ("TODO")
        }

    }
}
