/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TestPlanChangeModel
import org.openapitools.client.models.TestPlanChangedFieldsViewModel

class TestPlanChangeModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TestPlanChangeModel
        //val modelInstance = TestPlanChangeModel()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `testPlanId`
        should("test testPlanId") {
            // uncomment below to test the property
            //modelInstance.testPlanId shouldBe ("TODO")
        }

        // to test the property `testPlanChangedFields`
        should("test testPlanChangedFields") {
            // uncomment below to test the property
            //modelInstance.testPlanChangedFields shouldBe ("TODO")
        }

        // to test the property `createdById`
        should("test createdById") {
            // uncomment below to test the property
            //modelInstance.createdById shouldBe ("TODO")
        }

        // to test the property `createdDate`
        should("test createdDate") {
            // uncomment below to test the property
            //modelInstance.createdDate shouldBe ("TODO")
        }

    }
}
