/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WorkItemChangeModel
import org.openapitools.client.models.WorkItemChangedFieldsViewModel

class WorkItemChangeModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WorkItemChangeModel
        //val modelInstance = WorkItemChangeModel()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `workItemId`
        should("test workItemId") {
            // uncomment below to test the property
            //modelInstance.workItemId shouldBe ("TODO")
        }

        // to test the property `oldVersionId`
        should("test oldVersionId") {
            // uncomment below to test the property
            //modelInstance.oldVersionId shouldBe ("TODO")
        }

        // to test the property `newVersionId`
        should("test newVersionId") {
            // uncomment below to test the property
            //modelInstance.newVersionId shouldBe ("TODO")
        }

        // to test the property `workItemChangedFields`
        should("test workItemChangedFields") {
            // uncomment below to test the property
            //modelInstance.workItemChangedFields shouldBe ("TODO")
        }

        // to test the property `createdById`
        should("test createdById") {
            // uncomment below to test the property
            //modelInstance.createdById shouldBe ("TODO")
        }

        // to test the property `createdDate`
        should("test createdDate") {
            // uncomment below to test the property
            //modelInstance.createdDate shouldBe ("TODO")
        }

    }
}
