/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AutotestFilterModel
import org.openapitools.client.models.SearchAutoTestsQueryIncludesModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filter Object containing different filters to adjust search
 * @param includes Object specifying data to be included
 */


data class AutotestsSelectModel (

    /* Object containing different filters to adjust search */
    @Json(name = "filter")
    val filter: AutotestFilterModel,

    /* Object specifying data to be included */
    @Json(name = "includes")
    val includes: SearchAutoTestsQueryIncludesModel

) {


}

