/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique ID of the attribute template
 * @param name Custom attributes template name
 * @param customAttributeIds Collection of attribute IDs
 */


data class CustomAttributeTemplatePutModel (

    /* Unique ID of the attribute template */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Custom attributes template name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Collection of attribute IDs */
    @Json(name = "customAttributeIds")
    val customAttributeIds: kotlin.collections.Set<java.util.UUID>? = null

) {


}

