/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TagPostModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param projectId 
 * @param attributes 
 * @param tags 
 * @param startDate Used for analytics
 * @param endDate Used for analytics
 * @param description 
 * @param build 
 * @param productName 
 * @param hasAutomaticDurationTimer 
 */


data class TestPlanPostModel (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "projectId")
    val projectId: java.util.UUID,

    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Json(name = "tags")
    val tags: kotlin.collections.List<TagPostModel>? = null,

    /* Used for analytics */
    @Json(name = "startDate")
    val startDate: java.time.OffsetDateTime? = null,

    /* Used for analytics */
    @Json(name = "endDate")
    val endDate: java.time.OffsetDateTime? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "build")
    val build: kotlin.String? = null,

    @Json(name = "productName")
    val productName: kotlin.String? = null,

    @Json(name = "hasAutomaticDurationTimer")
    val hasAutomaticDurationTimer: kotlin.Boolean? = null

) {


}

