/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProjectTestPlansFilterModel
import org.openapitools.client.models.TestPlanExtractionModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filter 
 * @param extractionModel 
 */


data class TestPlanSelectModel (

    @Json(name = "filter")
    val filter: ProjectTestPlansFilterModel,

    @Json(name = "extractionModel")
    val extractionModel: TestPlanExtractionModel? = null

) {


}

