/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserRankModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param firstName 
 * @param lastName 
 * @param middleName 
 * @param userName 
 * @param displayName 
 * @param userType 
 * @param avatarUrl 
 * @param avatarMetadata 
 * @param isDeleted 
 * @param isDisabled 
 * @param isActiveStatusByEntity 
 * @param userRank 
 * @param providerId 
 */


data class UserWithRankModel (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "firstName")
    val firstName: kotlin.String,

    @Json(name = "lastName")
    val lastName: kotlin.String,

    @Json(name = "middleName")
    val middleName: kotlin.String,

    @Json(name = "userName")
    val userName: kotlin.String,

    @Json(name = "displayName")
    val displayName: kotlin.String,

    @Json(name = "userType")
    val userType: kotlin.String,

    @Json(name = "avatarUrl")
    val avatarUrl: kotlin.String,

    @Json(name = "avatarMetadata")
    val avatarMetadata: kotlin.String,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    @Json(name = "isDisabled")
    val isDisabled: kotlin.Boolean,

    @Json(name = "isActiveStatusByEntity")
    val isActiveStatusByEntity: kotlin.Boolean,

    @Json(name = "userRank")
    val userRank: UserRankModel,

    @Json(name = "providerId")
    val providerId: java.util.UUID? = null

) {


}

