/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.AIServiceModelApiResultGroup

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param groups 
 * @param totalCount 
 */


data class AIServiceModelApiResultGroupedReply (

    @Json(name = "groups")
    val groups: kotlin.collections.List<AIServiceModelApiResultGroup>,

    @Json(name = "totalCount")
    val totalCount: kotlin.Int

) {


}

