/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param dateTime 
 * @param userName 
 */


data class AuditApiResult (

    @Json(name = "userId")
    val userId: java.util.UUID,

    @Json(name = "dateTime")
    val dateTime: java.time.OffsetDateTime,

    @Json(name = "userName")
    val userName: kotlin.String? = null

) {


}

