/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.AttachmentPutModel
import ru.testit.kotlin.client.models.AttachmentPutModelAutoTestStepResultsModel
import ru.testit.kotlin.client.models.AvailableTestResultOutcome
import ru.testit.kotlin.client.models.FailureCategoryModel
import ru.testit.kotlin.client.models.LinkPostModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param configurationId Specifies the GUID of the autotest configuration, which was specified when the test run was created.
 * @param autoTestExternalId Specifies the external ID of the autotest, which was specified when the test run was created.
 * @param outcome Specifies the result of the autotest execution.
 * @param links Specifies the links in the autotest.
 * @param failureReasonNames Specifies the cause of autotest failure.
 * @param message A comment for the result.
 * @param traces An extended comment or a stack trace.
 * @param startedOn Test run start date.
 * @param completedOn Test run end date.
 * @param duration Expected or actual duration of the test run execution in milliseconds.
 * @param attachments Specifies an attachment GUID. Multiple values can be sent.
 * @param parameters \"<b>parameter</b>\": \"<b>value</b>\" pair with arbitrary custom parameters. Multiple parameters can be sent.
 * @param properties \"<b>property</b>\": \"<b>value</b>\" pair with arbitrary custom properties. Multiple properties can be sent.
 * @param stepResults Specifies the results of individual steps.
 * @param setupResults Specifies the results of setup steps. For information on supported values, see the `stepResults` parameter above.
 * @param teardownResults Specifies the results of the teardown steps. For information on supported values, see the `stepResults` parameter above.
 */


data class AutoTestResultsForTestRunModel (

    /* Specifies the GUID of the autotest configuration, which was specified when the test run was created. */
    @Json(name = "configurationId")
    val configurationId: java.util.UUID,

    /* Specifies the external ID of the autotest, which was specified when the test run was created. */
    @Json(name = "autoTestExternalId")
    val autoTestExternalId: kotlin.String,

    /* Specifies the result of the autotest execution. */
    @Json(name = "outcome")
    val outcome: AvailableTestResultOutcome,

    /* Specifies the links in the autotest. */
    @Json(name = "links")
    val links: kotlin.collections.List<LinkPostModel>? = null,

    /* Specifies the cause of autotest failure. */
    @Json(name = "failureReasonNames")
    val failureReasonNames: kotlin.collections.List<FailureCategoryModel>? = null,

    /* A comment for the result. */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* An extended comment or a stack trace. */
    @Json(name = "traces")
    val traces: kotlin.String? = null,

    /* Test run start date. */
    @Json(name = "startedOn")
    val startedOn: java.time.OffsetDateTime? = null,

    /* Test run end date. */
    @Json(name = "completedOn")
    val completedOn: java.time.OffsetDateTime? = null,

    /* Expected or actual duration of the test run execution in milliseconds. */
    @Json(name = "duration")
    val duration: kotlin.Long? = null,

    /* Specifies an attachment GUID. Multiple values can be sent. */
    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentPutModel>? = null,

    /* \"<b>parameter</b>\": \"<b>value</b>\" pair with arbitrary custom parameters. Multiple parameters can be sent. */
    @Json(name = "parameters")
    val parameters: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* \"<b>property</b>\": \"<b>value</b>\" pair with arbitrary custom properties. Multiple properties can be sent. */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Specifies the results of individual steps. */
    @Json(name = "stepResults")
    val stepResults: kotlin.collections.List<AttachmentPutModelAutoTestStepResultsModel>? = null,

    /* Specifies the results of setup steps. For information on supported values, see the `stepResults` parameter above. */
    @Json(name = "setupResults")
    val setupResults: kotlin.collections.List<AttachmentPutModelAutoTestStepResultsModel>? = null,

    /* Specifies the results of the teardown steps. For information on supported values, see the `stepResults` parameter above. */
    @Json(name = "teardownResults")
    val teardownResults: kotlin.collections.List<AttachmentPutModelAutoTestStepResultsModel>? = null

) {


}

