/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId Unique ID of the project.
 * @param rerunEnabled Auto rerun enabled
 * @param rerunAttemptsCount Auto rerun attempt count
 * @param isFlakyAuto Indicates if the status \"Flaky/Stable\" sets automatically
 * @param flakyStabilityPercentage Stability percentage for autotest flaky computing
 * @param flakyTestRunCount Last test run count for autotest flaky computing
 */


data class AutoTestProjectSettingsGetModel (

    /* Unique ID of the project. */
    @Json(name = "projectId")
    val projectId: java.util.UUID,

    /* Auto rerun enabled */
    @Json(name = "rerunEnabled")
    val rerunEnabled: kotlin.Boolean,

    /* Auto rerun attempt count */
    @Json(name = "rerunAttemptsCount")
    val rerunAttemptsCount: kotlin.Int,

    /* Indicates if the status \"Flaky/Stable\" sets automatically */
    @Json(name = "isFlakyAuto")
    val isFlakyAuto: kotlin.Boolean? = false,

    /* Stability percentage for autotest flaky computing */
    @Json(name = "flakyStabilityPercentage")
    val flakyStabilityPercentage: kotlin.Int? = 100,

    /* Last test run count for autotest flaky computing */
    @Json(name = "flakyTestRunCount")
    val flakyTestRunCount: kotlin.Int? = 100

) {


}

