/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param classes Autotest classnames
 * @param name Autotest namespace
 */


data class AutoTestNamespaceApiResult (

    /* Autotest classnames */
    @Json(name = "classes")
    val classes: kotlin.collections.List<kotlin.String>,

    /* Autotest namespace */
    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

