/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.CollectionOperator
import ru.testit.kotlin.client.models.IFilter

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `operator` 
 * @param filter 
 * @param `field` 
 */


data class CollectionFilter (

    @Json(name = "operator")
    val `operator`: CollectionOperator,

    @Json(name = "filter")
    val filter: IFilter,

    @Json(name = "field")
    val `field`: kotlin.String

) {


}

