/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.IFilter
import ru.testit.kotlin.client.models.LogicalOperator

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filters 
 * @param `operator` 
 */


data class CompositeFilter (

    @Json(name = "filters")
    val filters: kotlin.collections.List<IFilter>,

    @Json(name = "operator")
    val `operator`: LogicalOperator

) {


}

