/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.ConfigurationParameterProjectApiModel
import ru.testit.kotlin.client.models.ConfigurationParameterValueApiModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Name of the configuration parameter, must be unique
 * @param propertyValues List of possible configuration parameter values
 * @param projects List of projects to which configuration parameter should be assigned
 */


data class ConfigurationParameterApiModel (

    /* Name of the configuration parameter, must be unique */
    @Json(name = "name")
    val name: kotlin.String,

    /* List of possible configuration parameter values */
    @Json(name = "values")
    val propertyValues: kotlin.collections.List<ConfigurationParameterValueApiModel>,

    /* List of projects to which configuration parameter should be assigned */
    @Json(name = "projects")
    val projects: kotlin.collections.List<ConfigurationParameterProjectApiModel>? = null

) {


}

