/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.GuidExtractionModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ids Extraction parameters for configurations
 * @param projectIds Extraction parameters for projects
 */


data class ConfigurationExtractionApiModel (

    /* Extraction parameters for configurations */
    @Json(name = "ids")
    val ids: GuidExtractionModel? = null,

    /* Extraction parameters for projects */
    @Json(name = "projectIds")
    val projectIds: GuidExtractionModel? = null

) {


}

