/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.ExternalIssuePriorityModel
import ru.testit.kotlin.client.models.ExternalIssueTypeModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param code 
 * @param description 
 * @param status 
 * @param assignee 
 * @param type 
 * @param priority 
 */


data class ExternalIssueMetadataModel (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "assignee")
    val assignee: kotlin.String? = null,

    @Json(name = "type")
    val type: ExternalIssueTypeModel? = null,

    @Json(name = "priority")
    val priority: ExternalIssuePriorityModel? = null

) {


}

