/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.ExternalIssueMetadataModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param externalId 
 * @param url 
 * @param metadata 
 */


data class ExternalIssueModel (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "externalId")
    val externalId: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "metadata")
    val metadata: ExternalIssueMetadataModel

) {


}

