/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.ExternalIssueApiFieldSuggestion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param totalCount 
 */


data class ExternalIssueApiFieldSuggestionReply (

    @Json(name = "data")
    val `data`: kotlin.collections.List<ExternalIssueApiFieldSuggestion>,

    @Json(name = "totalCount")
    val totalCount: kotlin.Int

) {


}

