/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.ExternalIssueApiMetadata

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Identiief of external issue
 * @param externalId Identifier of external issue in external service
 * @param url Url of external issue
 * @param metadata Metadata of external issue from external service
 */


data class ExternalIssueApiResult (

    /* Identiief of external issue */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Identifier of external issue in external service */
    @Json(name = "externalId")
    val externalId: kotlin.String,

    /* Url of external issue */
    @Json(name = "url")
    val url: kotlin.String,

    /* Metadata of external issue from external service */
    @Json(name = "metadata")
    val metadata: ExternalIssueApiMetadata

) {


}

