/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param count Group entries count
 * @param fieldValue Group field value
 * @param displayFieldValue Group display field value
 */


data class FailureCategoryGroupApiResult (

    /* Group entries count */
    @Json(name = "count")
    val count: kotlin.Int,

    /* Group field value */
    @Json(name = "fieldValue")
    val fieldValue: kotlin.Any? = null,

    /* Group display field value */
    @Json(name = "displayFieldValue")
    val displayFieldValue: kotlin.Any? = null

) {


}

