/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: Equal,ExclamationEqual,Tilde,ExclamationTilde,Less_Than,Less_ThanEqual,Greater_Than,Greater_ThanEqual,Star,ExclamationStar
 */

@JsonClass(generateAdapter = false)
enum class FilterOperator(val value: kotlin.String) {

    @Json(name = "=")
    Equal("="),

    @Json(name = "!=")
    ExclamationEqual("!="),

    @Json(name = "~")
    Tilde("~"),

    @Json(name = "!~")
    ExclamationTilde("!~"),

    @Json(name = "<")
    Less_Than("<"),

    @Json(name = "<=")
    Less_ThanEqual("<="),

    @Json(name = ">")
    Greater_Than(">"),

    @Json(name = ">=")
    Greater_ThanEqual(">="),

    @Json(name = "*")
    Star("*"),

    @Json(name = "!*")
    ExclamationStar("!*");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is FilterOperator) "$data" else null

        /**
         * Returns a valid [FilterOperator] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): FilterOperator? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

