/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: Undefined,Object,Array,String,Number,True,False,Null
 */

@JsonClass(generateAdapter = false)
enum class JsonValueKind(val value: kotlin.String) {

    @Json(name = "Undefined")
    Undefined("Undefined"),

    @Json(name = "Object")
    Object("Object"),

    @Json(name = "Array")
    Array("Array"),

    @Json(name = "String")
    String("String"),

    @Json(name = "Number")
    Number("Number"),

    @Json(name = "True")
    True("True"),

    @Json(name = "False")
    False("False"),

    @Json(name = "Null")
    Null("Null");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is JsonValueKind) "$data" else null

        /**
         * Returns a valid [JsonValueKind] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): JsonValueKind? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

