/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param parameterKeyIds 
 * @param name 
 * @param isDeleted 
 * @param projectIds 
 */


data class ParameterGroupsFilterApiModel (

    @Json(name = "parameterKeyIds")
    val parameterKeyIds: kotlin.collections.Set<java.util.UUID>? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @Json(name = "projectIds")
    val projectIds: kotlin.collections.List<java.util.UUID>? = null

) {


}

