/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.FailureCategory

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Failure category identifier
 * @param failureCategory Category type
 * @param createdDate Failure category creation date
 * @param createdById Failure category creator identifier
 * @param projectsCount Projects relations count
 * @param failureCategoryId Category type index
 * @param regexCount Regexes count
 * @param name Failure category name
 * @param modifiedDate Failure category last modification date
 * @param modifiedById Failure category last modifier identifier
 */


data class ProjectFailureCategoryApiResult (

    /* Failure category identifier */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Category type */
    @Json(name = "failureCategory")
    val failureCategory: FailureCategory,

    /* Failure category creation date */
    @Json(name = "createdDate")
    val createdDate: java.time.OffsetDateTime,

    /* Failure category creator identifier */
    @Json(name = "createdById")
    val createdById: java.util.UUID,

    /* Projects relations count */
    @Json(name = "projectsCount")
    val projectsCount: kotlin.Int,

    /* Category type index */
    @Json(name = "failureCategoryId")
    val failureCategoryId: kotlin.Int,

    /* Regexes count */
    @Json(name = "regexCount")
    val regexCount: kotlin.Int,

    /* Failure category name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Failure category last modification date */
    @Json(name = "modifiedDate")
    val modifiedDate: java.time.OffsetDateTime? = null,

    /* Failure category last modifier identifier */
    @Json(name = "modifiedById")
    val modifiedById: java.util.UUID? = null

) {


}

