/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Name of the project
 * @param description Description of the project
 * @param isFavorite Indicates if the project is marked as favorite
 */


data class ProjectPostModel (

    /* Name of the project */
    @Json(name = "name")
    val name: kotlin.String,

    /* Description of the project */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Indicates if the project is marked as favorite */
    @Json(name = "isFavorite")
    val isFavorite: kotlin.Boolean? = null

) {


}

