/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param attachmentId Identifier of attachment with JUnit XML to import
 * @param configurationId Identifier of configuration. Uses default configuration in project if omitted.
 * @param layerName Name of test pyramid layer to set. Uses rules if omitted.
 */


data class ScheduleAutoTestsReportImportApiModel (

    /* Identifier of attachment with JUnit XML to import */
    @Json(name = "attachmentId")
    val attachmentId: java.util.UUID,

    /* Identifier of configuration. Uses default configuration in project if omitted. */
    @Json(name = "configurationId")
    val configurationId: java.util.UUID? = null,

    /* Name of test pyramid layer to set. Uses rules if omitted. */
    @Json(name = "layerName")
    val layerName: kotlin.String? = null

) {


}

