/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.FieldFilter
import ru.testit.kotlin.client.models.Inquiry

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectIds 
 * @param inquiry 
 * @param valuesFilters 
 * @param projectsFilters 
 */


data class SearchConfigurationParametersApiModel (

    @Json(name = "projectIds")
    val projectIds: kotlin.collections.List<java.util.UUID>? = null,

    @Json(name = "inquiry")
    val inquiry: Inquiry? = null,

    @Json(name = "valuesFilters")
    val valuesFilters: kotlin.collections.List<FieldFilter>? = null,

    @Json(name = "projectsFilters")
    val projectsFilters: kotlin.collections.List<FieldFilter>? = null

) {


}

