/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.DateTimeRangeSelectorModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Specifies a tag name to search for
 * @param createdDate Specifies a tag range of creation date to search for
 * @param createdByIds Specifies a tag creator IDs to search for
 */


data class TagsFilterModel (

    /* Specifies a tag name to search for */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Specifies a tag range of creation date to search for */
    @Json(name = "createdDate")
    val createdDate: DateTimeRangeSelectorModel? = null,

    /* Specifies a tag creator IDs to search for */
    @Json(name = "createdByIds")
    val createdByIds: kotlin.collections.Set<java.util.UUID>? = null

) {


}

