/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param statusCode 
 * @param statusName 
 * @param `value` 
 */


data class TestPlanTestPointsStatusCodeGroupApiResult (

    @Json(name = "statusCode")
    val statusCode: kotlin.String,

    @Json(name = "statusName")
    val statusName: kotlin.String,

    @Json(name = "value")
    val `value`: kotlin.Long

) {


}

