/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.TestPlanTestPointsGroupApiResult
import ru.testit.kotlin.client.models.TestPlanTestPointsSearchApiResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param group 
 * @param items 
 */


data class TestPlanTestPointsGroupSearchItemApiResult (

    @Json(name = "group")
    val group: TestPlanTestPointsGroupApiResult?,

    @Json(name = "items")
    val items: kotlin.collections.List<TestPlanTestPointsSearchApiResult>

) {


}

