/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.TestSuiteType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param testPlanId Unique ID of test plan to which the test suite belongs
 * @param name Name of the test suite
 * @param parentId Unique ID of the parent test suite in hierarchy
 * @param type Type of the test suite
 * @param saveStructure Indicates if the test suite retains section tree structure
 * @param autoRefresh Indicates if scheduled auto refresh is enabled for the test suite
 */


data class TestSuiteV2PostModel (

    /* Unique ID of test plan to which the test suite belongs */
    @Json(name = "testPlanId")
    val testPlanId: java.util.UUID,

    /* Name of the test suite */
    @Json(name = "name")
    val name: kotlin.String,

    /* Unique ID of the parent test suite in hierarchy */
    @Json(name = "parentId")
    val parentId: java.util.UUID? = null,

    /* Type of the test suite */
    @Json(name = "type")
    val type: TestSuiteType? = null,

    /* Indicates if the test suite retains section tree structure */
    @Json(name = "saveStructure")
    val saveStructure: kotlin.Boolean? = null,

    /* Indicates if scheduled auto refresh is enabled for the test suite */
    @Json(name = "autoRefresh")
    val autoRefresh: kotlin.Boolean? = null

) {


}

