/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.TestPlanTestPointsStatusCodeGroupApiResult
import ru.testit.kotlin.client.models.TestStatusApiType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param statusType Collection of possible status types
 * @param statuses 
 */


data class TestPlanTestPointsTesterAndStatusTypeGroupApiResult (

    @Json(name = "userId")
    val userId: java.util.UUID?,

    /* Collection of possible status types */
    @Json(name = "statusType")
    val statusType: TestStatusApiType,

    @Json(name = "statuses")
    val statuses: kotlin.collections.List<TestPlanTestPointsStatusCodeGroupApiResult>

) {


}

