/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.AuditApiResult
import ru.testit.kotlin.client.models.TestPlanTestPointsSectionSearchApiResult
import ru.testit.kotlin.client.models.WorkItemPriority
import ru.testit.kotlin.client.models.WorkItemState

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param globalId 
 * @param versionId 
 * @param versionNumber 
 * @param duration 
 * @param state 
 * @param tags 
 * @param attributes 
 * @param isAutomated 
 * @param name 
 * @param priority 
 * @param section 
 * @param created 
 * @param medianDuration 
 * @param isDeleted 
 * @param orderRank 
 * @param modified 
 */


data class TestPlanTestPointsWorkItemSearchApiResult (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "globalId")
    val globalId: kotlin.Long,

    @Json(name = "versionId")
    val versionId: java.util.UUID,

    @Json(name = "versionNumber")
    val versionNumber: kotlin.Int,

    @Json(name = "duration")
    val duration: kotlin.Int,

    @Json(name = "state")
    val state: WorkItemState,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Json(name = "isAutomated")
    val isAutomated: kotlin.Boolean,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "priority")
    val priority: WorkItemPriority,

    @Json(name = "section")
    val section: TestPlanTestPointsSectionSearchApiResult,

    @Json(name = "created")
    val created: AuditApiResult,

    @Json(name = "medianDuration")
    val medianDuration: kotlin.Long? = null,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @Json(name = "orderRank")
    val orderRank: kotlin.String? = null,

    @Json(name = "modified")
    val modified: AuditApiResult? = null

) {


}

