/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: New,InProgress,Paused,Completed
 */

@JsonClass(generateAdapter = false)
enum class TestPlanStatus(val value: kotlin.String) {

    @Json(name = "New")
    New("New"),

    @Json(name = "InProgress")
    InProgress("InProgress"),

    @Json(name = "Paused")
    Paused("Paused"),

    @Json(name = "Completed")
    Completed("Completed");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TestPlanStatus) "$data" else null

        /**
         * Returns a valid [TestPlanStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TestPlanStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

