/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Test run id.
 * @param name Test run name.
 */


data class TestRunNameApiResult (

    /* Test run id. */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Test run name. */
    @Json(name = "name")
    val name: kotlin.String

) {


}

