/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: Custom,Dynamic,Tree
 */

@JsonClass(generateAdapter = false)
enum class TestSuiteTypeApiResult(val value: kotlin.String) {

    @Json(name = "Custom")
    Custom("Custom"),

    @Json(name = "Dynamic")
    Dynamic("Dynamic"),

    @Json(name = "Tree")
    Tree("Tree");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TestSuiteTypeApiResult) "$data" else null

        /**
         * Returns a valid [TestSuiteTypeApiResult] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TestSuiteTypeApiResult? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

