/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param webhookIds Enabled webhooks.
 * @param customParameters Customers test run parameters.
 */


data class TestRunLaunchOptionApiModel (

    /* Enabled webhooks. */
    @Json(name = "webhookIds")
    val webhookIds: kotlin.collections.List<java.util.UUID>,

    /* Customers test run parameters. */
    @Json(name = "customParameters")
    val customParameters: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

