/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param score 
 * @param workItemsCreated 
 * @param passedTestPoints 
 * @param failedTestPoints 
 * @param skippedTestPoints 
 * @param blockedTestPoints 
 * @param levelAvatarEnabled 
 */


data class UserRankModel (

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "workItemsCreated")
    val workItemsCreated: kotlin.Int,

    @Json(name = "passedTestPoints")
    val passedTestPoints: kotlin.Int,

    @Json(name = "failedTestPoints")
    val failedTestPoints: kotlin.Int,

    @Json(name = "skippedTestPoints")
    val skippedTestPoints: kotlin.Int,

    @Json(name = "blockedTestPoints")
    val blockedTestPoints: kotlin.Int,

    @Json(name = "levelAvatarEnabled")
    val levelAvatarEnabled: kotlin.Boolean

) {


}

