/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id ID of the comment
 * @param text Text of the comment
 * @param createdById ID of user created comment
 * @param modifiedById ID of user modified comment
 * @param createdDate Comment created date
 * @param modifiedDate Comment modified date
 */


data class WorkItemCommentApiResult (

    /* ID of the comment */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Text of the comment */
    @Json(name = "text")
    val text: kotlin.String,

    /* ID of user created comment */
    @Json(name = "createdById")
    val createdById: java.util.UUID,

    /* ID of user modified comment */
    @Json(name = "modifiedById")
    val modifiedById: java.util.UUID,

    /* Comment created date */
    @Json(name = "createdDate")
    val createdDate: java.time.OffsetDateTime,

    /* Comment modified date */
    @Json(name = "modifiedDate")
    val modifiedDate: java.time.OffsetDateTime

) {


}

