/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.WorkItemExtractionModel
import ru.testit.kotlin.client.models.WorkItemLocalFilterModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Model containing options to filter work items
 *
 * @param filter Collection of filters to apply to search
 * @param extractionModel Rules for different level entities inclusion/exclusion
 */


data class WorkItemLocalSelectModel (

    /* Collection of filters to apply to search */
    @Json(name = "filter")
    val filter: WorkItemLocalFilterModel? = null,

    /* Rules for different level entities inclusion/exclusion */
    @Json(name = "extractionModel")
    val extractionModel: WorkItemExtractionModel? = null

) {


}

