/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currentIndex Current index (position) of the element in a collection
 * @param totalCount Total count of elements in a collection
 */


data class WorkItemIndexApiResult (

    /* Current index (position) of the element in a collection */
    @Json(name = "currentIndex")
    val currentIndex: kotlin.Long,

    /* Total count of elements in a collection */
    @Json(name = "totalCount")
    val totalCount: kotlin.Long

) {


}

