/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.AttachmentChangeViewModelArrayChangedFieldViewModel
import ru.testit.kotlin.client.models.AutoTestChangeViewModelArrayChangedFieldViewModel
import ru.testit.kotlin.client.models.BooleanChangedFieldViewModel
import ru.testit.kotlin.client.models.GuidChangedFieldViewModel
import ru.testit.kotlin.client.models.Int32ChangedFieldViewModel
import ru.testit.kotlin.client.models.Int64ChangedFieldViewModel
import ru.testit.kotlin.client.models.StringArrayChangedFieldViewModel
import ru.testit.kotlin.client.models.StringChangedFieldViewModel
import ru.testit.kotlin.client.models.StringChangedFieldWithDiffsViewModel
import ru.testit.kotlin.client.models.WorkItemChangedAttributeViewModel
import ru.testit.kotlin.client.models.WorkItemLinkChangeViewModelArrayChangedFieldViewModel
import ru.testit.kotlin.client.models.WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isDeleted 
 * @param projectId 
 * @param isAutomated 
 * @param sectionId 
 * @param state 
 * @param priority 
 * @param duration 
 * @param attributes 
 * @param steps 
 * @param preconditionSteps 
 * @param postconditionSteps 
 * @param autoTests 
 * @param attachments 
 * @param tags 
 * @param links 
 * @param globalId 
 * @param versionNumber 
 * @param entityTypeName 
 * @param name 
 * @param description 
 */


data class WorkItemChangedFieldsViewModel (

    @Json(name = "isDeleted")
    val isDeleted: BooleanChangedFieldViewModel,

    @Json(name = "projectId")
    val projectId: GuidChangedFieldViewModel,

    @Json(name = "isAutomated")
    val isAutomated: BooleanChangedFieldViewModel,

    @Json(name = "sectionId")
    val sectionId: GuidChangedFieldViewModel,

    @Json(name = "state")
    val state: StringChangedFieldViewModel,

    @Json(name = "priority")
    val priority: StringChangedFieldViewModel,

    @Json(name = "duration")
    val duration: Int32ChangedFieldViewModel,

    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, WorkItemChangedAttributeViewModel>,

    @Json(name = "steps")
    val steps: WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel,

    @Json(name = "preconditionSteps")
    val preconditionSteps: WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel,

    @Json(name = "postconditionSteps")
    val postconditionSteps: WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel,

    @Json(name = "autoTests")
    val autoTests: AutoTestChangeViewModelArrayChangedFieldViewModel,

    @Json(name = "attachments")
    val attachments: AttachmentChangeViewModelArrayChangedFieldViewModel,

    @Json(name = "tags")
    val tags: StringArrayChangedFieldViewModel,

    @Json(name = "links")
    val links: WorkItemLinkChangeViewModelArrayChangedFieldViewModel,

    @Json(name = "globalId")
    val globalId: Int64ChangedFieldViewModel,

    @Json(name = "versionNumber")
    val versionNumber: Int32ChangedFieldViewModel,

    @Json(name = "entityTypeName")
    val entityTypeName: StringChangedFieldViewModel,

    @Json(name = "name")
    val name: StringChangedFieldWithDiffsViewModel? = null,

    @Json(name = "description")
    val description: StringChangedFieldWithDiffsViewModel? = null

) {


}

