/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import ru.testit.kotlin.client.models.WorkItemExternalMetadataFieldFilterModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ids Identifiers of external issues to search for
 * @param types Types of external issues to search for
 * @param priorities Priorities of external issues to search for
 * @param statuses Statuses of external issues to search for
 * @param assignees Assignees of external issues to search for
 */


data class WorkItemExternalMetadataFilterModel (

    /* Identifiers of external issues to search for */
    @Json(name = "ids")
    val ids: kotlin.collections.List<WorkItemExternalMetadataFieldFilterModel>? = null,

    /* Types of external issues to search for */
    @Json(name = "types")
    val types: kotlin.collections.List<WorkItemExternalMetadataFieldFilterModel>? = null,

    /* Priorities of external issues to search for */
    @Json(name = "priorities")
    val priorities: kotlin.collections.List<WorkItemExternalMetadataFieldFilterModel>? = null,

    /* Statuses of external issues to search for */
    @Json(name = "statuses")
    val statuses: kotlin.collections.List<WorkItemExternalMetadataFieldFilterModel>? = null,

    /* Assignees of external issues to search for */
    @Json(name = "assignees")
    val assignees: kotlin.collections.List<WorkItemExternalMetadataFieldFilterModel>? = null

) {


}

