/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ru.testit.kotlin.client.models.ConfigurationExtractionModel
import ru.testit.kotlin.client.models.GuidExtractionModel

class ConfigurationExtractionModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigurationExtractionModel
        //val modelInstance = ConfigurationExtractionModel()

        // to test the property `ids` - Extraction parameters for configurations
        should("test ids") {
            // uncomment below to test the property
            //modelInstance.ids shouldBe ("TODO")
        }

        // to test the property `projectIds` - Extraction parameters for projects
        should("test projectIds") {
            // uncomment below to test the property
            //modelInstance.projectIds shouldBe ("TODO")
        }

    }
}
