/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ru.testit.kotlin.client.models.GetXlsxTestPointsByTestPlanModel

class GetXlsxTestPointsByTestPlanModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetXlsxTestPointsByTestPlanModel
        //val modelInstance = GetXlsxTestPointsByTestPlanModel()

        // to test the property `includeName`
        should("test includeName") {
            // uncomment below to test the property
            //modelInstance.includeName shouldBe ("TODO")
        }

        // to test the property `includeSection`
        should("test includeSection") {
            // uncomment below to test the property
            //modelInstance.includeSection shouldBe ("TODO")
        }

        // to test the property `includePriority`
        should("test includePriority") {
            // uncomment below to test the property
            //modelInstance.includePriority shouldBe ("TODO")
        }

        // to test the property `includeAutomated`
        should("test includeAutomated") {
            // uncomment below to test the property
            //modelInstance.includeAutomated shouldBe ("TODO")
        }

        // to test the property `includeStatus`
        should("test includeStatus") {
            // uncomment below to test the property
            //modelInstance.includeStatus shouldBe ("TODO")
        }

        // to test the property `includeDuration`
        should("test includeDuration") {
            // uncomment below to test the property
            //modelInstance.includeDuration shouldBe ("TODO")
        }

        // to test the property `includeCreationDate`
        should("test includeCreationDate") {
            // uncomment below to test the property
            //modelInstance.includeCreationDate shouldBe ("TODO")
        }

        // to test the property `includeAuthor`
        should("test includeAuthor") {
            // uncomment below to test the property
            //modelInstance.includeAuthor shouldBe ("TODO")
        }

        // to test the property `includeModificationDate`
        should("test includeModificationDate") {
            // uncomment below to test the property
            //modelInstance.includeModificationDate shouldBe ("TODO")
        }

        // to test the property `includeModifiedBy`
        should("test includeModifiedBy") {
            // uncomment below to test the property
            //modelInstance.includeModifiedBy shouldBe ("TODO")
        }

        // to test the property `includeTags`
        should("test includeTags") {
            // uncomment below to test the property
            //modelInstance.includeTags shouldBe ("TODO")
        }

        // to test the property `includeIterations`
        should("test includeIterations") {
            // uncomment below to test the property
            //modelInstance.includeIterations shouldBe ("TODO")
        }

        // to test the property `customAttributesIds`
        should("test customAttributesIds") {
            // uncomment below to test the property
            //modelInstance.customAttributesIds shouldBe ("TODO")
        }

        // to test the property `configurationIds`
        should("test configurationIds") {
            // uncomment below to test the property
            //modelInstance.configurationIds shouldBe ("TODO")
        }

    }
}
