/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ru.testit.kotlin.client.models.ProjectTypeModel

class ProjectTypeModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectTypeModel
        //val modelInstance = ProjectTypeModel()

    }
}
