/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ru.testit.kotlin.client.models.TestResultStepCommentPutModel
import ru.testit.kotlin.client.models.AttachmentPutModel

class TestResultStepCommentPutModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TestResultStepCommentPutModel
        //val modelInstance = TestResultStepCommentPutModel()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `text`
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

        // to test the property `stepId`
        should("test stepId") {
            // uncomment below to test the property
            //modelInstance.stepId shouldBe ("TODO")
        }

        // to test the property `attachments`
        should("test attachments") {
            // uncomment below to test the property
            //modelInstance.attachments shouldBe ("TODO")
        }

        // to test the property `parentStepId`
        should("test parentStepId") {
            // uncomment below to test the property
            //modelInstance.parentStepId shouldBe ("TODO")
        }

    }
}
