/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ru.testit.kotlin.client.models.WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel
import ru.testit.kotlin.client.models.WorkItemStepChangeViewModel

class WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel
        //val modelInstance = WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel()

        // to test the property `diffValue`
        should("test diffValue") {
            // uncomment below to test the property
            //modelInstance.diffValue shouldBe ("TODO")
        }

        // to test the property `oldValue`
        should("test oldValue") {
            // uncomment below to test the property
            //modelInstance.oldValue shouldBe ("TODO")
        }

        // to test the property `newValue`
        should("test newValue") {
            // uncomment below to test the property
            //modelInstance.newValue shouldBe ("TODO")
        }

    }
}
