/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ru.testit.kotlin.client.models.WorkItemChangedFieldsViewModel
import ru.testit.kotlin.client.models.AttachmentChangeViewModelArrayChangedFieldViewModel
import ru.testit.kotlin.client.models.AutoTestChangeViewModelArrayChangedFieldViewModel
import ru.testit.kotlin.client.models.BooleanChangedFieldViewModel
import ru.testit.kotlin.client.models.GuidChangedFieldViewModel
import ru.testit.kotlin.client.models.Int32ChangedFieldViewModel
import ru.testit.kotlin.client.models.Int64ChangedFieldViewModel
import ru.testit.kotlin.client.models.StringArrayChangedFieldViewModel
import ru.testit.kotlin.client.models.StringChangedFieldViewModel
import ru.testit.kotlin.client.models.StringChangedFieldWithDiffsViewModel
import ru.testit.kotlin.client.models.WorkItemChangedAttributeViewModel
import ru.testit.kotlin.client.models.WorkItemLinkChangeViewModelArrayChangedFieldViewModel
import ru.testit.kotlin.client.models.WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel

class WorkItemChangedFieldsViewModelTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WorkItemChangedFieldsViewModel
        //val modelInstance = WorkItemChangedFieldsViewModel()

        // to test the property `isDeleted`
        should("test isDeleted") {
            // uncomment below to test the property
            //modelInstance.isDeleted shouldBe ("TODO")
        }

        // to test the property `projectId`
        should("test projectId") {
            // uncomment below to test the property
            //modelInstance.projectId shouldBe ("TODO")
        }

        // to test the property `isAutomated`
        should("test isAutomated") {
            // uncomment below to test the property
            //modelInstance.isAutomated shouldBe ("TODO")
        }

        // to test the property `sectionId`
        should("test sectionId") {
            // uncomment below to test the property
            //modelInstance.sectionId shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `priority`
        should("test priority") {
            // uncomment below to test the property
            //modelInstance.priority shouldBe ("TODO")
        }

        // to test the property `duration`
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `attributes`
        should("test attributes") {
            // uncomment below to test the property
            //modelInstance.attributes shouldBe ("TODO")
        }

        // to test the property `steps`
        should("test steps") {
            // uncomment below to test the property
            //modelInstance.steps shouldBe ("TODO")
        }

        // to test the property `preconditionSteps`
        should("test preconditionSteps") {
            // uncomment below to test the property
            //modelInstance.preconditionSteps shouldBe ("TODO")
        }

        // to test the property `postconditionSteps`
        should("test postconditionSteps") {
            // uncomment below to test the property
            //modelInstance.postconditionSteps shouldBe ("TODO")
        }

        // to test the property `autoTests`
        should("test autoTests") {
            // uncomment below to test the property
            //modelInstance.autoTests shouldBe ("TODO")
        }

        // to test the property `attachments`
        should("test attachments") {
            // uncomment below to test the property
            //modelInstance.attachments shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `links`
        should("test links") {
            // uncomment below to test the property
            //modelInstance.links shouldBe ("TODO")
        }

        // to test the property `globalId`
        should("test globalId") {
            // uncomment below to test the property
            //modelInstance.globalId shouldBe ("TODO")
        }

        // to test the property `versionNumber`
        should("test versionNumber") {
            // uncomment below to test the property
            //modelInstance.versionNumber shouldBe ("TODO")
        }

        // to test the property `entityTypeName`
        should("test entityTypeName") {
            // uncomment below to test the property
            //modelInstance.entityTypeName shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
