/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.api

import io.kotlintest.specs.ShouldSpec

class SectionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SectionsApi
        //val apiInstance = SectionsApi()

        // to test apiV2SectionsIdPatch
        should("test apiV2SectionsIdPatch") {
            // uncomment below to test apiV2SectionsIdPatch
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | Section internal (UUID) identifier
            //val operation : kotlin.collections.List<Operation> =  // kotlin.collections.List<Operation> | 
            //apiInstance.apiV2SectionsIdPatch(id, operation)
        }

        // to test createSection
        should("test createSection") {
            // uncomment below to test createSection
            //val sectionPostModel : SectionPostModel =  // SectionPostModel | 
            //val result : SectionWithStepsModel = apiInstance.createSection(sectionPostModel)
            //result shouldBe ("TODO")
        }

        // to test deleteSection
        should("test deleteSection") {
            // uncomment below to test deleteSection
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | Section internal (UUID) identifier
            //apiInstance.deleteSection(id)
        }

        // to test getSectionById
        should("test getSectionById") {
            // uncomment below to test getSectionById
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | Section internal (UUID) identifier
            //val isDeleted : DeletionState =  // DeletionState | 
            //val result : SectionWithStepsModel = apiInstance.getSectionById(id, isDeleted)
            //result shouldBe ("TODO")
        }

        // to test getWorkItemsBySectionId
        should("test getWorkItemsBySectionId") {
            // uncomment below to test getWorkItemsBySectionId
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | Section internal (UUID) identifier
            //val isDeleted : kotlin.Boolean = true // kotlin.Boolean | Requested section is deleted
            //val tagNames : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | List of work item tags
            //val includeIterations : kotlin.Boolean = true // kotlin.Boolean | 
            //val skip : kotlin.Int = 56 // kotlin.Int | Amount of items to be skipped (offset)
            //val take : kotlin.Int = 56 // kotlin.Int | Amount of items to be taken (limit)
            //val orderBy : kotlin.String = orderBy_example // kotlin.String | SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
            //val searchField : kotlin.String = searchField_example // kotlin.String | Property name for searching
            //val searchValue : kotlin.String = searchValue_example // kotlin.String | Value for searching
            //val result : kotlin.collections.List<WorkItemShortModel> = apiInstance.getWorkItemsBySectionId(id, isDeleted, tagNames, includeIterations, skip, take, orderBy, searchField, searchValue)
            //result shouldBe ("TODO")
        }

        // to test move
        should("test move") {
            // uncomment below to test move
            //val sectionMoveModel : SectionMoveModel =  // SectionMoveModel | 
            //apiInstance.move(sectionMoveModel)
        }

        // to test rename
        should("test rename") {
            // uncomment below to test rename
            //val sectionRenameModel : SectionRenameModel =  // SectionRenameModel | 
            //apiInstance.rename(sectionRenameModel)
        }

        // to test updateSection
        should("test updateSection") {
            // uncomment below to test updateSection
            //val sectionPutModel : SectionPutModel =  // SectionPutModel | 
            //apiInstance.updateSection(sectionPutModel)
        }

    }
}
