/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.client.api

import io.kotlintest.specs.ShouldSpec

class TagsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TagsApi
        //val apiInstance = TagsApi()

        // to test apiV2TagsDelete
        should("test apiV2TagsDelete") {
            // uncomment below to test apiV2TagsDelete
            //val tagSelectModel : TagSelectModel =  // TagSelectModel | 
            //apiInstance.apiV2TagsDelete(tagSelectModel)
        }

        // to test apiV2TagsGet
        should("test apiV2TagsGet") {
            // uncomment below to test apiV2TagsGet
            //val result : kotlin.collections.List<TagModel> = apiInstance.apiV2TagsGet()
            //result shouldBe ("TODO")
        }

        // to test apiV2TagsIdDelete
        should("test apiV2TagsIdDelete") {
            // uncomment below to test apiV2TagsIdDelete
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | Tag internal (UUID) identifier
            //apiInstance.apiV2TagsIdDelete(id)
        }

        // to test apiV2TagsPost
        should("test apiV2TagsPost") {
            // uncomment below to test apiV2TagsPost
            //val tagPostModel : TagPostModel =  // TagPostModel | 
            //val result : TagModel = apiInstance.apiV2TagsPost(tagPostModel)
            //result shouldBe ("TODO")
        }

        // to test apiV2TagsPut
        should("test apiV2TagsPut") {
            // uncomment below to test apiV2TagsPut
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val tagPutModel : TagPutModel =  // TagPutModel | 
            //val result : TagModel = apiInstance.apiV2TagsPut(id, tagPutModel)
            //result shouldBe ("TODO")
        }

        // to test apiV2TagsSearchGet
        should("test apiV2TagsSearchGet") {
            // uncomment below to test apiV2TagsSearchGet
            //val skip : kotlin.Int = 56 // kotlin.Int | Amount of items to be skipped (offset)
            //val take : kotlin.Int = 56 // kotlin.Int | Amount of items to be taken (limit)
            //val orderBy : kotlin.String = orderBy_example // kotlin.String | SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
            //val searchField : kotlin.String = searchField_example // kotlin.String | Property name for searching
            //val searchValue : kotlin.String = searchValue_example // kotlin.String | Value for searching
            //val result : kotlin.collections.List<TagModel> = apiInstance.apiV2TagsSearchGet(skip, take, orderBy, searchField, searchValue)
            //result shouldBe ("TODO")
        }

        // to test apiV2TagsTestPlansTagsGet
        should("test apiV2TagsTestPlansTagsGet") {
            // uncomment below to test apiV2TagsTestPlansTagsGet
            //val skip : kotlin.Int = 56 // kotlin.Int | Amount of items to be skipped (offset)
            //val take : kotlin.Int = 56 // kotlin.Int | Amount of items to be taken (limit)
            //val orderBy : kotlin.String = orderBy_example // kotlin.String | SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC)
            //val searchField : kotlin.String = searchField_example // kotlin.String | Property name for searching
            //val searchValue : kotlin.String = searchValue_example // kotlin.String | Value for searching
            //val result : kotlin.collections.List<TagModel> = apiInstance.apiV2TagsTestPlansTagsGet(skip, take, orderBy, searchField, searchValue)
            //result shouldBe ("TODO")
        }

    }
}
